apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-deployment
  labels:
    app: gemini
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gemini
  template:
    metadata:
      labels:
        app: gemini
    spec:
      containers:
      - name: gemini-container
        image: patil2624/gemini
        ports:
          - containerPort: 2624
